apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: persistent-volume
  resources:
    requests:
      storage: 1Gi