apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/brandonbautista/Documents/ChatApp/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem